### ISSUE TITLE
Share Card Design

### ISSUE THREAD

**Issue by WolfGarden** [BlackMalrangcow/blackmalrangcow-frontend#1]
https://drive.google.com/file/d/1acx57Epe7ATdXYaPzy_nfCNMSRo0kgH2/view?usp=sharing

**Comment by ENvironmentSet** [comment]
Thx, @rlacjfwns  this can be molecule. IMO, we have to split this as some atoms.

**Comment by ENvironmentSet** [comment]
And, @WolfGarden  what is that circle in the design? can you explain about it?

**Comment by WolfGarden** [comment]
It's a picture. Writer will be able to upload.

**Comment by WolfGarden** [comment]
https://drive.google.com/file/d/1acx57Epe7ATdXYaPzy_nfCNMSRo0kgH2/view?usp=sharing
@ENvironmentSet  @rlacjfwns 
NEW

**Comment by WolfGarden** [comment]
https://drive.google.com/file/d/1acx57Epe7ATdXYaPzy_nfCNMSRo0kgH2/view?usp=sharing

@ENvironmentSet 

Smaller card.  read this

**Comment by ENvironmentSet** [comment]
#10
