### ISSUE TITLE
Share Title Design (Template)

### ISSUE THREAD

**Issue by WolfGarden** [BlackMalrangcow/blackmalrangcow-frontend#3]
https://drive.google.com/file/d/1oF78fGCN8i1ds0witc_uLdDd2ZkMLdRw/view?usp=sharing

NEED HELP

@ENvironmentSet

**Comment by ENvironmentSet** [comment]
you should split those components as atom and molecule.
to confuse to see.

@WolfGarden

**Comment by WolfGarden** [comment]
You mean, split all those components and write informations to all of components?
srry, idk what you mean.

@ENvironmentSet

**Comment by WolfGarden** [comment]
@ENvironmentSet 
Which picture is comfortable, round one or square one?

**Comment by ENvironmentSet** [comment]
I mean, we need to split those components, like.

Login page = form component + title component
from component = id component + password component

@WolfGarden

**Comment by ENvironmentSet** [comment]
I mean, there is too many things on the design blueprint.

@WolfGarden

**Comment by ENvironmentSet** [comment]
#10
