### ISSUE TITLE
Card Design

### ISSUE THREAD

**Issue by WolfGarden** [BlackMalrangcow/blackmalrangcow-frontend#5]
https://drive.google.com/file/d/1acx57Epe7ATdXYaPzy_nfCNMSRo0kgH2/view?usp=sharing

Tell me more.

**Comment by ENvironmentSet** [comment]
By my memory, that square picture should be circle image.

@WolfGarden

**Comment by ENvironmentSet** [comment]
we have to make decision in #1 about this.
