### ISSUE TITLE
Fixing CircleImage component's style

### ISSUE THREAD

**Issue by ENvironmentSet** [BlackMalrangcow/blackmalrangcow-frontend#6]
@WolfGarden has update blueprint of card news.
and he added explicitly description for CircleImage. 

So, we have to fix CircleImage component.

@rlacjfwns can you do this?

**Comment by WolfGarden** [comment]
Need anything else?

**Comment by ENvironmentSet** [comment]
@WolfGarden  Nothing, just I hope your design is correct.

**Comment by rlacjfwns** [comment]
Check

**Comment by ENvironmentSet** [comment]
@rlacjfwns thx, plz make PR for this.

**Comment by ENvironmentSet** [comment]
@rlacjfwns and.. you should remove `display: 'block',`. because it's useless.

**Comment by ENvironmentSet** [comment]
#10
